// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Data;

#nullable disable

namespace Portfolio.Migrations
{
    [DbContext(typeof(SkillsDbContext))]
    [Migration("20260409043314_AddSkillsTable")]
    partial class AddSkillsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Portfolio.Models.SkillsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SkillsLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Backend",
                            Name = "C/C++"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Backend",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Frontend",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Frontend",
                            Name = "React"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Frontend",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Frontend",
                            Name = "CSS/Tailwind CSS"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Frontend",
                            Name = "Material UI/Bootstrap/Font Awesome"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Tools",
                            Name = "Version Control - Git"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Tools",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Tools",
                            Name = "Postman"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Tools",
                            Name = "Playwright"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
